# Generated by Django 3.0.10 on 2020-10-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themesettings',
            options={'verbose_name': 'Theme'},
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='About address'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_phone',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='About email'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='about_short_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='About short description'),
        ),
    ]
