# Generated by Django 3.0.8 on 2020-07-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='search_image',
        ),
    ]
