# Generated by Django 3.0.8 on 2020-07-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200722_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='search_image',
        ),
    ]
