# Generated by Django 3.0.8 on 2020-07-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_formpage_search_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='button_text',
            field=models.CharField(default='Anfrage senden', max_length=50),
            preserve_default=False,
        ),
    ]
