# Generated by Django 3.0.8 on 2020-07-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogtagindexpage_search_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtagindexpage',
            name='search_image',
        ),
    ]
