# Generated by Django 3.0.10 on 2020-10-31 19:13

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blogauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BlogAuthor'),
        ),
    ]
