# Generated by Django 3.0.10 on 2020-10-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_blogpage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='description',
            field=models.TextField(default='lorem impsum', max_length=500),
            preserve_default=False,
        ),
    ]
