# Generated by Django 3.0.8 on 2020-07-19 10:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_auto_20200719_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='body',
            field=wagtail.core.fields.StreamField([('grid', wagtail.core.blocks.StructBlock([('column', wagtail.core.blocks.MultipleChoiceBlock(choices=[('tea', 'Tea'), ('coffee', 'Coffee')]))]))]),
        ),
    ]
