# Generated by Django 3.0.8 on 2020-07-19 15:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0009_auto_20200719_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('row', wagtail.core.blocks.StructBlock([('layout', wagtail.core.blocks.MultipleChoiceBlock(choices=[('test', 'test2'), ('test', 'test2'), ('test', 'test2'), ('test', 'test2'), ('test', 'test2'), ('test', 'test2'), ('test', 'test2'), ('test', 'test2'), ('test', 'test2'), ('test', 'test2'), ('test', 'test2'), ('test', 'test2')])), ('carousel', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('quotation', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('author', wagtail.core.blocks.CharBlock())])), ('video', wagtail.embeds.blocks.EmbedBlock())], icon='cogs'))], icon='user'))]),
        ),
    ]
