# Generated by Django 3.0.10 on 2020-10-16 23:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0011_flexpage_search_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Flex Page'},
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('hero_section_block', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(default='Super Awesome Feature', label='Feature', max_length=80, required=True)), ('section_subheading', wagtail.core.blocks.CharBlock(default='Super Awesome Hero Subheading', label='Subheading', max_length=100, required=False)), ('description', wagtail.core.blocks.TextBlock(default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', label='Description', max_length=400, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image', required=False))]))], blank=True, null=True),
        ),
    ]
