# Generated by Django 3.0.10 on 2020-10-18 12:53

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0013_auto_20201017_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('page_heading_section_block', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(default='Super Awesome Sect', label='Heading', max_length=80, required=False))])), ('hero_section_block', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(default='Super Awesome Feature', label='Feature', max_length=80, required=False)), ('subheading', wagtail.core.blocks.CharBlock(default='Super Awesome Hero Subheading', label='Subheading', max_length=100, required=False)), ('description', wagtail.core.blocks.TextBlock(default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', label='Description', max_length=400, required=False)), ('button', wagtail.core.blocks.CharBlock(default='Get in touch', label='Button text', max_length=20, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image', required=False))])), ('logo_cloud_block', wagtail.core.blocks.StructBlock([('logos', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])))])), ('service_section_block', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(label='Title', max_length=100, required=True)), ('services', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('logo', wagtail.core.blocks.RawHTMLBlock(required=True)), ('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('description', wagtail.core.blocks.TextBlock(max_length=300, required=True))])))])), ('feature_section_block', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(label='Title', max_length=100, required=True)), ('features', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.RawHTMLBlock(required=True, rows=5)), ('heading', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('description', wagtail.core.blocks.TextBlock(max_length=300, required=True))])))])), ('counter_section_block', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(label='Title', max_length=100, required=True)), ('counters', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.TextBlock(max_length=300, required=True)), ('count', wagtail.core.blocks.IntegerBlock(max_value=1000000, required=True))])))])), ('cta_section_block', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(default='Super Awesome Product', label='Heading', max_length=80, required=False)), ('description', wagtail.core.blocks.TextBlock(default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', label='Description', max_length=400, required=False)), ('button', wagtail.core.blocks.CharBlock(default='Get in touch', label='Button text', max_length=20, required=False))])), ('pricing_section_block', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(label='Title', max_length=100, required=True)), ('pricings', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.TextBlock(max_length=300, required=True)), ('price', wagtail.core.blocks.IntegerBlock(max_value=100000, required=True)), ('storage', wagtail.core.blocks.IntegerBlock(max_value=100000, required=True)), ('hosting', wagtail.core.blocks.BooleanBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
