# Generated by Django 3.0.10 on 2020-10-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('flex', '0014_auto_20201018_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlexPage',
        ),
    ]
