# Generated by Django 3.0.10 on 2020-10-18 12:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_search_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('page_heading_section_block', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(default='Super Awesome Sect', label='Heading', max_length=80, required=False))]))], blank=True, null=True),
        ),
    ]
